name: env-gmda
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib==3.5.1
  - numpy==1.21.2
  - numba==0.55.1
  - pandas==1.4.1
  - scikit_learn==1.0.2
  - seaborn==0.12.2
  - setuptools==58.0.4
  - torch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - umap_learn==0.5.2
  - rich==13.3.5